Update .zshrc

diff --git a/dot_zshrc.tmpl b/dot_zshrc.tmpl
--- a/dot_zshrc.tmpl
+++ b/dot_zshrc.tmpl
@@ -105,6 +105,30 @@ fi
 
 reset() { if [ "$#" -lt 2 ]; then echo "Usage: reset branch-name file1 [file2 ... fileN]"; return 1; fi; local branch_name=$1; shift; for file in "$@"; do git checkout "$branch_name" -- "$file"; if [ $? -ne 0 ]; then echo "Failed to reset $file"; return 1; fi; done; git status; echo -n "Do you want to commit the changes? (yes/no) "; read confirmation; if [[ "$confirmation" == "yes" ]]; then git add "$@"; git commit -m "Reset changes to branch $branch_name" --no-verify; else echo "Changes not committed."; fi; }
 
+squash() {
+    if [ "$#" -ne 1 ]; then
+        echo "Usage: squash_commits num_commits"
+        return 1
+    fi
+    local num_commits=$1
+    echo "The following commits will be squashed:"
+    git log -n "$num_commits" --oneline
+    echo -n "Do you want to squash these commits? (yes/no) "
+    read confirmation
+    if [[ "$confirmation" != "yes" ]]; then
+        echo "Commit squash aborted."
+        return 1
+    fi
+    git reset --soft HEAD~"$num_commits" &&
+    git commit --reuse-message=HEAD@{1}
+    if [ $? -eq 0 ]; then
+        echo "Commits successfully squashed."
+    else
+        echo "Failed to squash commits. Please resolve any conflicts and try again."
+    fi
+}
+
+
 export NVM_DIR="$HOME/.nvm"
 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
 [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
