Update .zshrc

diff --git a/dot_zshrc.tmpl b/dot_zshrc.tmpl
--- a/dot_zshrc.tmpl
+++ b/dot_zshrc.tmpl
@@ -103,6 +103,8 @@ if [[ -f /home/fisher/bin/tinymodt/data/motd ]]; then
     cat /home/fisher/bin/tinymodt/data/motd
 fi
 
+reset() { if [ "$#" -lt 2 ]; then echo "Usage: reset branch-name file1 [file2 ... fileN]"; return 1; fi; local branch_name=$1; shift; for file in "$@"; do git checkout "$branch_name" -- "$file"; if [ $? -ne 0 ]; then echo "Failed to reset $file"; return 1; fi; done; git status; echo -n "Do you want to commit the changes? (yes/no) "; read confirmation; if [[ "$confirmation" == "yes" ]]; then git add "$@"; git commit -m "Reset changes to branch $branch_name" --no-verify; else echo "Changes not committed."; fi; }
+
 export NVM_DIR="$HOME/.nvm"
 [ -s "$NVM_DIR/nvm.sh" ] && \. "$NVM_DIR/nvm.sh"  # This loads nvm
 [ -s "$NVM_DIR/bash_completion" ] && \. "$NVM_DIR/bash_completion"  # This loads nvm bash_completion
