Update run_once_after_vim-config.sh.tmpl

diff --git a/run_once_after_vim-config.sh.tmpl b/run_once_after_vim-config.sh.tmpl
--- a/run_once_after_vim-config.sh.tmpl
+++ b/run_once_after_vim-config.sh.tmpl
@@ -5,10 +5,19 @@ plugin_install () {
 }
 
 compile_ycm() {
-	cd $HOME/.vim/bundle/YouCompleteMe
-    /usr/bin/env python3 install.py --system-libclang --all
+    local canonical_python=$(which python3)
+
+    popd $HOME/.vim/bundle/YouCompleteMe
+    $canonical_python install.py --system-libclang --all
+    		
 }
 
-compile_ycm
-plugin_install
+if [[ $(compile_ycm) -eq 0 ]]; then
+   if [[ $(plugin_install) -eq 0]]; then
+	exit 0;
+   fi
+else
+   echo -e "Compilation and plugin installation failed!"
+   exit 1;
+fi
 
